# Generated by Django 2.2.6 on 2020-02-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0002_auto_20200207_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='image',
            field=models.ImageField(null=True, upload_to='land_img'),
        ),
    ]
