# Generated by Django 2.2.6 on 2020-02-07 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0003_land_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
