# Generated by Django 2.2.6 on 2020-02-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0006_auto_20200207_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='image',
            field=models.ImageField(null=True, upload_to='land_img'),
        ),
    ]
