# Generated by Django 2.2.6 on 2020-02-07 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0007_auto_20200207_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='land',
            name='image',
        ),
    ]
