# Generated by Django 2.2.6 on 2020-02-07 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0010_land_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='image',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
